MAP_MAPPING = {
    "The Sewerways + Golden Hands Desert Base",
    "Thanatara Canyon + Gurun Desert",
    "Oasis",
    "Morose",
    "Verdawn Forest + Misty Maze",
    "Travoll Industrial Park",
    "Copperwood",
    "Ana Thema",
    "Gloamwood",
    "The Plagued Forest",
    "Ulvosa",
    "Snowveil + Verglas Village",
    "Verdazure Sea (West) + Outer Moat + Solanda Beach",
    "Verdazure Sea (East) + Forgotten City + Gothera Swamplands (East)",
    "Tartarus",
    "Snowveilian Valley + Desert Hands HQ",
    "Magma Pits + Magma Depths + Gothera Swamplands (West)",
    "Snowveil + Dreamer's Keep",
    "Heaven's Valley (East) + Valhalla's Breath (East)",
    "Valhalla",
    "Heaven's Valley (West) + Valhalla's Breath (West)",
    "The Solennian Ruins",
    "Sinner's Oath + Phantasmic Palace",
    "The Relicts",
    "The Catacombs + Omphalos Laboratory",
    "Cloister of Redemption",
    "Gallery of Mirrors + Gallery of Souls",
    "Blushwood",
    "Evernight Garden"
}